const form = document.querySelector("#risk-form");

const fields = {
  bmi: document.querySelector("#bmi-value"),
  ost: document.querySelector("#ost-value"),
  label: document.querySelector("#prediction-label"),
  recommendation: document.querySelector("#recommendation"),
  modelStatus: document.querySelector("#model-status"),
  modeNote: document.querySelector("#mode-note"),
  shapTitle: document.querySelector("#shap-title"),
  shapCaption: document.querySelector("#shap-caption"),
  shapPlot: document.querySelector("#shap-plot"),
  bars: {
    normal: document.querySelector("#bar-normal"),
    osteopenia: document.querySelector("#bar-osteopenia"),
    osteoporosis: document.querySelector("#bar-osteoporosis"),
  },
  probs: {
    normal: document.querySelector("#prob-normal"),
    osteopenia: document.querySelector("#prob-osteopenia"),
    osteoporosis: document.querySelector("#prob-osteoporosis"),
  },
};

const isLocalStaticPreview = ["127.0.0.1", "localhost"].includes(window.location.hostname);
const API_URL =
  window.OSTEOML_API_URL ||
  (isLocalStaticPreview ? "http://127.0.0.1:8038/api/predict" : `${window.location.origin}/api/predict`);

const APP_TEXT = {
  labels: {
    normal: "Normal tendency",
    osteopenia: "Osteopenia tendency",
    osteoporosis: "Osteoporosis tendency",
  },
  recommendations: {
    normal:
      "Current inputs suggest lower screening risk. Continue routine assessment according to age and clinical context.",
    osteopenia:
      "Current inputs suggest increased risk for low bone mass. Consider DXA referral based on clinician judgement.",
    osteoporosis:
      "Current inputs suggest high osteoporosis screening risk. DXA confirmation should be considered.",
  },
  estimatedProbability: "Estimated class probability:",
  statusReady: "Prediction ready",
  statusPreview: "Preview only",
  statusCalculating: "Calculating...",
  statusCalculatingShap: "Calculating risk and SHAP...",
  statusInputChanged: "Input updated; click calculate",
  modeActual:
    "This result is generated by the prediction service. It is intended for research communication and screening discussion, not diagnosis.",
  modeDemo:
    "This is a browser preview. Click the calculate button to generate the full prediction and SHAP plots.",
  shapInitialTitle: "Native SHAP plots appear after calculation",
  shapInitialCaption:
    "Click the calculate button to generate native SHAP plots for the current prediction.",
  shapTitle(className) {
    return `Native SHAP plots for ${className}`;
  },
  shapCaption(method, baseValue, outputValue) {
    return `${method}. Base probability ${formatPercent(baseValue)} plus feature contributions gives ${formatPercent(outputValue)} for this class.`;
  },
};

let lastResult = null;
let lastMode = "demo";

function text() {
  return APP_TEXT;
}

function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}

function asNumber(formData, key) {
  return Number.parseFloat(formData.get(key));
}

function normalizeScores(scores) {
  const total = scores.normal + scores.osteopenia + scores.osteoporosis;
  return {
    normal: scores.normal / total,
    osteopenia: scores.osteopenia / total,
    osteoporosis: scores.osteoporosis / total,
  };
}

function calculateRisk(data) {
  const heightM = data.height / 100;
  const bmi = data.weight / (heightM * heightM);
  const ost = Math.floor(0.2 * (data.weight - data.age));

  const ageRisk = clamp((data.age - 45) / 35, 0, 1);
  const lowBmiRisk = bmi < 18.5 ? 0.24 : bmi < 23 ? 0.13 : bmi < 28 ? 0.06 : 0.02;
  const ostRisk = ost <= -3 ? 0.34 : ost <= 1 ? 0.17 : 0.04;
  const sexRisk = data.sex === "female" ? 0.07 : 0.025;
  const raceRisk =
    data.race === "asian"
      ? 0.035
      : data.race === "non_hispanic_black"
        ? -0.025
        : data.race === "mexican_american" || data.race === "other_hispanic"
          ? 0.015
          : 0;
  const alpRisk = data.alp > 130 ? 0.11 : data.alp > 95 ? 0.05 : 0;
  const renalRisk = data.creatinine > 110 ? 0.05 : 0;
  const pressureRisk = data.sbp > 150 ? 0.03 : 0;
  const activityRisk = data.activity === "low" ? 0.06 : data.activity === "high" ? -0.03 : 0;
  const calciumRisk = data.calcium < 500 ? 0.04 : data.calcium > 1200 ? -0.015 : 0;

  const osteoporosis =
    0.05 +
    ageRisk * 0.25 +
    lowBmiRisk +
    ostRisk +
    sexRisk +
    raceRisk +
    alpRisk +
    renalRisk +
    calciumRisk +
    activityRisk;

  const osteopenia =
    0.22 +
    ageRisk * 0.22 +
    (ost <= 1 ? 0.12 : 0.02) +
    (bmi < 23 ? 0.08 : 0.03) +
    pressureRisk -
    Math.max(osteoporosis - 0.55, 0) * 0.2;

  const normal =
    0.5 +
    (bmi >= 23 && bmi <= 30 ? 0.12 : 0) +
    (ost > 1 ? 0.18 : 0) +
    (data.activity === "high" ? 0.06 : 0) -
    ageRisk * 0.24 -
    lowBmiRisk;

  return {
    bmi,
    ost,
    probabilities: normalizeScores({
      normal: clamp(normal, 0.03, 0.9),
      osteopenia: clamp(osteopenia, 0.05, 0.86),
      osteoporosis: clamp(osteoporosis, 0.02, 0.9),
    }),
  };
}

function formatPercent(value) {
  return `${Math.round(value * 100)}%`;
}

function normalizeApiProbabilities(probabilities) {
  return {
    normal: Number(probabilities.Normal ?? probabilities.normal ?? 0),
    osteopenia: Number(probabilities.Osteopenia ?? probabilities.osteopenia ?? 0),
    osteoporosis: Number(probabilities.Osteoporosis ?? probabilities.osteoporosis ?? 0),
  };
}

function renderShap(explanation) {
  if (!fields.shapPlot || !fields.shapTitle || !fields.shapCaption) return;

  const copy = text();
  if (!explanation?.plots?.length) {
    fields.shapTitle.textContent = copy.shapInitialTitle;
    fields.shapCaption.textContent = copy.shapInitialCaption;
    fields.shapPlot.innerHTML = "";
    return;
  }

  fields.shapTitle.textContent = copy.shapTitle(explanation.class_name);
  fields.shapCaption.textContent = copy.shapCaption(
    explanation.method,
    explanation.base_value,
    explanation.output_value,
  );

  fields.shapPlot.innerHTML = explanation.plots
    .map((plot) => {
      return `
        <figure class="native-shap-figure">
          <img src="${plot.src}" alt="${plot.title}">
          <figcaption>${plot.title}</figcaption>
        </figure>
      `;
    })
    .join("");
}

function render(result, mode = "demo") {
  if (!result || !fields.label) return;

  lastResult = result;
  lastMode = mode;

  const copy = text();
  const p = result.probabilities;
  const entries = Object.entries(p);
  const [prediction, probability] = entries.sort((a, b) => b[1] - a[1])[0];

  if (fields.bmi) fields.bmi.textContent = result.bmi.toFixed(1);
  if (fields.ost) fields.ost.textContent = String(result.ost);
  fields.label.textContent = copy.labels[prediction];
  if (fields.recommendation) {
    fields.recommendation.textContent = `${copy.recommendations[prediction]} ${copy.estimatedProbability} ${formatPercent(probability)}.`;
  }

  if (fields.modelStatus) {
    fields.modelStatus.textContent = mode === "actual_model" ? copy.statusReady : copy.statusPreview;
    fields.modelStatus.classList.toggle("online", mode === "actual_model");
    fields.modelStatus.classList.toggle("fallback", mode !== "actual_model");
  }

  if (fields.modeNote) {
    fields.modeNote.textContent = mode === "actual_model" ? copy.modeActual : copy.modeDemo;
  }

  for (const key of Object.keys(fields.bars)) {
    if (fields.bars[key]) fields.bars[key].style.width = formatPercent(p[key]);
    if (fields.probs[key]) fields.probs[key].textContent = formatPercent(p[key]);
  }

  renderShap(result.explanation);
}

function readForm() {
  const formData = new FormData(form);
  return {
    sex: formData.get("sex"),
    race: formData.get("race"),
    age: asNumber(formData, "age"),
    height: asNumber(formData, "height"),
    weight: asNumber(formData, "weight"),
    waist: asNumber(formData, "waist"),
    sbp: asNumber(formData, "sbp"),
    dbp: asNumber(formData, "dbp"),
    alp: asNumber(formData, "alp"),
    calcium: asNumber(formData, "calcium"),
    creatinine: asNumber(formData, "creatinine"),
    energy: asNumber(formData, "energy") || 1900,
    education: asNumber(formData, "education") || 3,
    income: asNumber(formData, "income") || 2,
    activity: formData.get("activity"),
  };
}

async function predictWithApi(data, includeShap = false) {
  const response = await fetch(API_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...data, include_shap: includeShap }),
  });
  if (!response.ok) {
    throw new Error(`Model API returned ${response.status}`);
  }
  const payload = await response.json();
  const probabilities = normalizeApiProbabilities(payload.probabilities);
  return {
    bmi: Number(payload.derived?.BMI ?? calculateRisk(data).bmi),
    ost: Number(payload.derived?.OST ?? calculateRisk(data).ost),
    probabilities,
    explanation: payload.explanation,
  };
}

async function updatePrediction(includeShap = false) {
  const data = readForm();
  if (fields.modelStatus) {
    fields.modelStatus.textContent = includeShap ? text().statusCalculatingShap : text().statusCalculating;
  }
  try {
    const result = await predictWithApi(data, includeShap);
    render(result, "actual_model");
  } catch {
    render(calculateRisk(data), "demo");
  }
}

if (form) {
  form.addEventListener("submit", (event) => {
    event.preventDefault();
    updatePrediction(true);
  });

  form.addEventListener("input", () => {
    const result = calculateRisk(readForm());
    render(result, "demo");
    if (fields.modelStatus) {
      fields.modelStatus.textContent = text().statusInputChanged;
      fields.modelStatus.classList.add("fallback");
      fields.modelStatus.classList.remove("online");
    }
    renderShap(null);
  });

  updatePrediction(false);
}

window.addEventListener("osteoml-language-change", () => {
  if (lastResult) {
    render(lastResult, lastMode);
  }
});
